name: Build project
description: Build the project with Conan and CMake dependencies

inputs:
  build_type:
    description: Project build type
    type: string
    required: true
  configure_preset:
    description: Configuration preset for Conan2
    type: string
    required: true
  conan_preset:
    description: Build preset for Conan2
    type: string
    required: true

runs:
  using: composite
  steps:
    - name: 'Setup default conan profile'
      shell: bash
      run: conan profile detect --force
    
    - name: 'Install project dependencies'
      shell: bash
      run: conan install . -s:a build_type=${{ inputs.build_type }} -s:a compiler.cppstd=23 --build=missing
    
    - name: 'CMake configuration phase'
      shell: bash
      run: cmake --preset ${{ inputs.configure_preset }}
    
    - name: 'CMake build phase'
      shell: bash
      run: cmake --build --preset ${{ inputs.conan_preset }}
