name: CI/CD

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      build_type:
        required: true
        type: string
      configure_preset:
        required: true
        type: string
      conan_preset:
        required: true
        type: string
      compiler:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Cloning git repository
        uses: actions/checkout@v4

      - name: Setup C++ infrastructure
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ inputs.compiler }}
          cmake: true
          conan: true
      
      - name: Build project
        uses: ./.github/actions/build-project
        with:
          build_type: ${{ inputs.build_type }}
          configure_preset: ${{ inputs.configure_preset }}
          conan_preset: ${{ inputs.conan_preset }}
  
  test:
    runs-on: ${{ inputs.os }}
    needs:
      - build
    steps:
      - name: Cloning git repository
        uses: actions/checkout@v4
      
      - name: Setup C++ dependencies
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ inputs.compiler }}
          cmake: true
          conan: true
      
      - name: Build project
        uses: ./.github/actions/build-project
        with:
          build_type: ${{ inputs.build_type }}
          configure_preset: ${{ inputs.configure_preset }}
          conan_preset: ${{ inputs.conan_preset }}
      
      - name: Unit-testing
        run: ctest --preset ${{ inputs.conan_preset }}
  
  save-artifact:
    runs-on: ${{ inputs.os }}
    needs:
      - test
    steps:
      - name: Cloning git repository
        uses: actions/checkout@v4
      
      - name: Make archive
        run: tar -czf cxx-utilities-${{ runner.os }}.tar.gz --exclude=".git" --exclude=".github" ./*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-cxx-utilities-${{ runner.os }}
          path: ./cxx-utilities-${{ runner.os }}.tar.gz
          retention-days: 5
          overwrite: true

  release:
    runs-on: ${{ inputs.os }}
    permissions:
      contents: write
    needs:
      - save-artifact
    if: github.event_name == 'pull_request' && github.base_ref == 'master' && github.head_ref == 'dev' && github.event.pull_request.merged == true
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        
      - name: Download archive
        uses: actions/download-artifact@v4
        with:
          name: artifact-cxx-utilities-${{ runner.os }}
          path: ./artifact
      
      - name: Read project version
        id: version
        run: |
          VERSION=$(cat VERSION | tr -d '[:space:]')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      
      - name:
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: v${{ steps.version.outputs.version }}
          files: ./artifact/cxx-utilities-${{ runner.os }}.tar.gz
          fail_on_unmatched_files: true
