name: ubuntu-24.04

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
      - reopened
    branches:
      - master
    paths-ignore:
      - .github/**
      - ./profiles/
  push:
    branches:
      - master
    paths-ignore:
      - .github/**
      - ./profiles/

jobs:
  ubuntu-build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - build_type: Release
            conan_preset: conan-release
          - build_type: Debug
            conan_preset: conan-debug
    uses: podumai/cxx-utilities/.github/workflows/ci.yml@master
    with:
      os: ubuntu-24.04
      build_type: ${{ matrix.build_type }}
      configure_preset: ${{ matrix.conan_preset }}
      conan_preset: ${{ matrix.conan_preset }}
      compiler: llvm-21
